# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25975848c92d475c194fb8cbcf5543fcca0808ec6b6dd9360951c18cda859002bdd7c5e5112b68e4084fc632a9a55a6376906283361a456003ba1590104a9879

test:
  secret_key_base: 54371a9f9e7db331902840d01b0f8900f01428f7b0d600d0ec69d9a0c17b2e78ff18c7002fee4efebb10c9b8a684d196e70a2ecdcdb4211e10f8727dd750ead6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
